// src/lib/plansData.ts
export const plans = [
  {
    id: '1',
    title: 'Q4 Market Expansion - EMEA',
    desc: 'Strategic entry into DACH regions focusing on localized content and compliance headers.',
    status: 'Active',
    progress: 68,
    risk: 'Low',
    owner: 'Sarah Chen',
    sections: 12,
    tasks: 45,
    depth: 'Complex',
    dependencies: 4,
    lastUpdated: '2h ago',
    velocity: 'up'
  },
  {
    id: '2',
    title: 'Infrastructure Migration: AWS to GCP',
    desc: 'Systematic migration of text-intelligence nodes and vector databases.',
    status: 'Blocked',
    progress: 32,
    risk: 'High',
    owner: 'Marcus Voss',
    sections: 8,
    tasks: 112,
    depth: 'Technical',
    dependencies: 14,
    lastUpdated: '1d ago',
    velocity: 'down'
  },
  {
    id: '3',
    title: 'Brand Refresh 2024',
    desc: 'Update to visual language and text planning framework across all touchpoints.',
    status: 'Draft',
    progress: 5,
    risk: 'Medium',
    owner: 'Elena Rossi',
    sections: 4,
    tasks: 12,
    depth: 'Simple',
    dependencies: 1,
    lastUpdated: '5m ago',
    velocity: 'neutral'
  },
  {
    id: '4',
    title: 'AI Knowledge Base Re-Architecture',
    desc: 'Rebuilding text knowledge graphs for scalable inference and retrieval.',
    status: 'Active',
    progress: 54,
    risk: 'Medium',
    owner: 'Daniel Park',
    sections: 9,
    tasks: 63,
    depth: 'Complex',
    dependencies: 6,
    lastUpdated: '4h ago',
    velocity: 'up'
  },
  {
    id: '5',
    title: 'Customer Onboarding Playbook',
    desc: 'Structured text flows for onboarding enterprise customers.',
    status: 'Active',
    progress: 81,
    risk: 'Low',
    owner: 'Nina Alvarez',
    sections: 6,
    tasks: 28,
    depth: 'Operational',
    dependencies: 2,
    lastUpdated: '1h ago',
    velocity: 'up'
  },
  {
    id: '6',
    title: 'Security Compliance Audit (SOC 2)',
    desc: 'Text-based documentation and execution for SOC 2 readiness.',
    status: 'Blocked',
    progress: 41,
    risk: 'High',
    owner: 'Tom Becker',
    sections: 10,
    tasks: 74,
    depth: 'Regulatory',
    dependencies: 9,
    lastUpdated: '3d ago',
    velocity: 'down'
  },
  {
    id: '7',
    title: 'Content Strategy – Thought Leadership',
    desc: 'Long-form content planning and execution cadence.',
    status: 'Active',
    progress: 23,
    risk: 'Medium',
    owner: 'Priya Mehta',
    sections: 5,
    tasks: 19,
    depth: 'Creative',
    dependencies: 1,
    lastUpdated: '30m ago',
    velocity: 'up'
  },
  {
    id: '8',
    title: 'Internal Tooling Automation',
    desc: 'Reducing manual planning overhead through automation.',
    status: 'Draft',
    progress: 10,
    risk: 'Low',
    owner: 'Alex Morgan',
    sections: 3,
    tasks: 9,
    depth: 'Simple',
    dependencies: 0,
    lastUpdated: '6h ago',
    velocity: 'neutral'
  },
  {
    id: '9',
    title: 'Annual OKR Alignment',
    desc: 'Cross-team alignment of planning objectives and execution metrics.',
    status: 'Active',
    progress: 76,
    risk: 'Low',
    owner: 'Ravi Shah',
    sections: 7,
    tasks: 34,
    depth: 'Strategic',
    dependencies: 3,
    lastUpdated: '1d ago',
    velocity: 'up'
  }
];
